# Generated by Django 4.2.20 on 2025-04-16 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MN', 'Medica-NEET'), ('IJ', 'IIT-JEE'), ('CA', 'CA'), ('AT', 'Architecture'), ('DG', 'Desugn'), ('CO', 'Commerce'), ('UP', 'UPSC'), ('CD', 'CDS')], max_length=2),
        ),
    ]
